name = "BrownianMotionTree"
uuid = "632aa462-75ab-11e9-1d5b-c98cbbf33a35"
authors = ["Sascha Timme <sascha.timme@gmail.com>"]
version = "0.1.0"

[deps]
DynamicPolynomials = "7c1d4256-1411-5781-91ec-d7bc3513ac07"
HomotopyContinuation = "f213a82b-91d6-5c5d-acf7-10f1c761b327"
